kind: pipeline
type: kubernetes
name: default

steps:
  - name: helm
    image: alpine/helm:3.10.0
    environment:
      REGISTRY_USERNAME:
        from_secret: REGISTRY_USERNAME
      REGISTRY_PASSWORD:
        from_secret: REGISTRY_PASSWORD
    commands:
      - helm registry login registry.ivanchenko.io -u $${REGISTRY_USERNAME} -p $${REGISTRY_PASSWORD}
      - chart=$$(helm package chart)
      - helm push $$(basename $${chart#*/}) oci://registry.ivanchenko.io/library