image:
  repository: tiltedphoques/st-reborn-server
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

port: 10578

stServerPassword: "change-me"
existingSecret: ""

config:
  Gameplay:
    fGoldLossFactor: 0
    bEnableXpSync: true
    bEnableItemDrops: false
    uTimeScale: 20
    bEnableDeathSystem: true
    bSyncPlayerHomes: false
    bEnablePvp: false
    bEnableGreetings: false
    uDifficulty: 4
  LiveServices:
    bAnnounceServer: false
  ModPolicy:
    bAllowMO2: true
    bAllowSKSE: true
    bEnableModCheck: false
  GameServer:
    sPassword: "${ST_SERVER_PASSWORD}"
    sServerName: "Dedicated Together Server"
    bPremiumMode: true
    uMaxPlayerCount: 8
    uPort: "{{ .Values.port }}"

service:
  type: NodePort
  nodePort: 31313
  annotations: {}

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
