apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "st-reborn.fullname" . }}
  labels:
    {{- include "st-reborn.labels" . | nindent 4 }}
data:
  entrypoint.sh: |-
     #!/bin/sh
     eval "echo \"$(cat /home/server/config/STServer_raw.ini)\"" > /home/server/config/STServer.ini
     ./SkyrimTogetherServer
  STServer_raw.ini: |-
    {{- range $section, $settings := .Values.config }}
    [{{ $section }}]
    {{- range $key, $val := $settings }}
    {{ $key }}={{ tpl ($val | toString) $ }}
    {{- end }}
    {{ end }}