apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "st-reborn.fullname" . }}
  labels:
    {{- include "st-reborn.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "st-reborn.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "st-reborn.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.port }}
              protocol: UDP
          volumeMounts:
            - name: server-conf
              mountPath: /home/server/config/STServer.ini
              subPath: STServer.ini
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: server-conf
          configMap:
            name: {{ include "st-reborn.fullname" . }}
            items:
              - key: STServer.ini
                path: STServer.ini
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
