apiVersion: v1
kind: Service
metadata:
  name: {{ include "st-reborn.fullname" . }}
  labels:
    {{- include "st-reborn.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 10578
      targetPort: 10578
      name: skyrimserver
  selector:
    {{- include "st-reborn.selectorLabels" . | nindent 4 }}
