apiVersion: v1
kind: Service
metadata:
  name: {{ include "st-reborn.fullname" . }}
  labels:
    {{- include "st-reborn.labels" . | nindent 4 }}
  {{- with .Values.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: LoadBalancer
  ports:
    - protocol: UDP
      port: 10578
      targetPort: 10578
  selector:
    {{- include "st-reborn.selectorLabels" . | nindent 4 }}
